# Generated by Django 5.0.3 on 2024-03-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hydroponics_manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="measurement_date",
            new_name="timestamp",
        ),
        migrations.AddField(
            model_name="hydroponicsystem",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="hydroponicsystem",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("AEROPONIC", "Aeroponic Systems"),
                    ("DRIPPER_FEED", "Dripper Feed Systems"),
                    ("EBB_AND_FLOOD", "Ebb & Flood System"),
                    ("NFT", "Nutrient Film Technique"),
                    ("POT", "POT CULTURE"),
                ],
                default="POT",
                help_text="Type of hydroponic system",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hydroponicsystem",
            name="water_capacity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
