# Generated by Django 5.0.3 on 2024-03-27 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "hydroponics_manager",
            "0002_rename_measurement_date_measurement_timestamp_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hydroponicsystem",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="measurement",
            options={"ordering": ["-timestamp"]},
        ),
    ]
